version: '3'

services:
  caravan_backend:
    container_name: caravan_backend
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=caravan_backend
    ports:
      - 5434:5432
    volumes:
      - ./pgdata:/var/lib/postgresql
